postgres-db:
  port: "5432"
  host: "localhost"
  name: "postgres"
  user: "user"
redis-db:
  port: "6379"
  host: "localhost"
minio:
  endpoint: minio:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket: mri-scans
  use_ssl: false